var annotated =
[
    [ "Aluno", "class_aluno.html", "class_aluno" ],
    [ "AlunoAntigo", "class_aluno_antigo.html", "class_aluno_antigo" ],
    [ "AlunoJaExiste", "class_aluno_ja_existe.html", "class_aluno_ja_existe" ],
    [ "AlunoNaoExiste", "class_aluno_nao_existe.html", "class_aluno_nao_existe" ],
    [ "Aula", "class_aula.html", "class_aula" ],
    [ "Automovel", "class_automovel.html", "class_automovel" ],
    [ "BinaryNode", "class_binary_node.html", "class_binary_node" ],
    [ "BST", "class_b_s_t.html", "class_b_s_t" ],
    [ "BSTItrIn", "class_b_s_t_itr_in.html", "class_b_s_t_itr_in" ],
    [ "BSTItrLevel", "class_b_s_t_itr_level.html", "class_b_s_t_itr_level" ],
    [ "BSTItrPost", "class_b_s_t_itr_post.html", "class_b_s_t_itr_post" ],
    [ "BSTItrPre", "class_b_s_t_itr_pre.html", "class_b_s_t_itr_pre" ],
    [ "ColecaoVazia", "class_colecao_vazia.html", "class_colecao_vazia" ],
    [ "eqAlunoAntigo", "structeq_aluno_antigo.html", "structeq_aluno_antigo" ],
    [ "Escola", "class_escola.html", "class_escola" ],
    [ "EscolaComRecursosInsuficientes", "class_escola_com_recursos_insuficientes.html", "class_escola_com_recursos_insuficientes" ],
    [ "hAlunoAntigo", "structh_aluno_antigo.html", "structh_aluno_antigo" ],
    [ "HoraInvalida", "class_hora_invalida.html", "class_hora_invalida" ],
    [ "InputEsperadoEraInt", "class_input_esperado_era_int.html", "class_input_esperado_era_int" ],
    [ "InputEsperadoEraString", "class_input_esperado_era_string.html", "class_input_esperado_era_string" ],
    [ "Instrutor", "class_instrutor.html", "class_instrutor" ],
    [ "InstrutorJaExiste", "class_instrutor_ja_existe.html", "class_instrutor_ja_existe" ],
    [ "InstrutorNaoExiste", "class_instrutor_nao_existe.html", "class_instrutor_nao_existe" ],
    [ "Ligeiro", "class_ligeiro.html", "class_ligeiro" ],
    [ "MatriculaInvalida", "class_matricula_invalida.html", "class_matricula_invalida" ],
    [ "Motociclo", "class_motociclo.html", "class_motociclo" ],
    [ "Oficina", "class_oficina.html", "class_oficina" ],
    [ "Pesado", "class_pesado.html", "class_pesado" ],
    [ "Pessoa", "class_pessoa.html", "class_pessoa" ],
    [ "Program", "class_program.html", "class_program" ],
    [ "Viatura", "class_viatura.html", "class_viatura" ],
    [ "ViaturaJaExiste", "class_viatura_ja_existe.html", "class_viatura_ja_existe" ]
];